spring:
  datasource:
    ds1:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://192.168.86.90:3306/recsys?tinyInt1isBit=false&useUnicode=true&characterEncoding=UTF-8
      username: devlop
      password: qwer1234
    ds2:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://192.168.86.90:3306/recsys1?tinyInt1isBit=false&useUnicode=true&characterEncoding=UTF-8
      username: devlop
      password: qwer1234